package thymeflow.utilities.timezone

/**
  * @author  David Montoya
  */
case class Abbreviation(abbreviation: String, zoneId: String, location: String, offset: String)

object Abbreviation {

  val abbreviations = Vector(
    Abbreviation("A", "Alpha Time Zone", "Military", "UTC+01:00"),
    Abbreviation("ACDT", "Australian Central Daylight Time", "Australia", "UTC+10:30"),
    Abbreviation("CDT", "Central Daylight Time", "", "UTC+10:30"),
    Abbreviation("CDST", "Central Daylight Savings Time", "", "UTC+10:30"),
    Abbreviation("ACST", "Australian Central Standard Time", "Australia", "UTC+09:30"),
    Abbreviation("CST", "Central Standard Time", "", "UTC+09:30"),
    Abbreviation("ACT", "Acre Time", "South America", "UTC-05:00"),
    Abbreviation("ACT", "Australian Central Time", "Australia", "UTC+10:30 / +9:30"),
    Abbreviation("ACWST", "Australian Central Western Standard Time", "Australia", "UTC+08:45"),
    Abbreviation("ADT", "Arabia Daylight Time", "Asia", "UTC+03:00"),
    Abbreviation("AST", "Arabia Summer Time", "", "UTC+03:00"),
    Abbreviation("ADT", "Atlantic Daylight Time", "North America", "UTC-03:00"),
    Abbreviation("ADST", "Atlantic Daylight Saving Time", "Atlantic", "UTC-03:00"),
    Abbreviation("AST", "Atlantic Summer Time", "", "UTC-03:00"),
    Abbreviation("HAA", "Heure Avancée de l'Atlantique (French)", "", "UTC-03:00"),
    Abbreviation("AEDT", "Australian Eastern Daylight Time", "Australia", "UTC+11:00"),
    //Abbreviation("EDT", "Eastern Daylight Time", "Pacific", "UTC+11:00"),
    Abbreviation("EDST", "Eastern Daylight Saving Time", "", "UTC+11:00"),
    Abbreviation("AEST", "Australian Eastern Standard Time", "Australia", "UTC+10:00"),
    //Abbreviation("EST", "Eastern Standard Time", "", "UTC+10:00"),
    Abbreviation("AET", "Australian Eastern Time", "", "UTC+10:00"),
    Abbreviation("AET", "Australian Eastern Time", "Australia", "UTC+11:00 / +10:00"),
    Abbreviation("AFT", "Afghanistan Time", "Asia", "UTC+04:30"),
    Abbreviation("AKDT", "Alaska Daylight Time", "North America", "UTC-08:00"),
    Abbreviation("ADST", "Alaska Daylight Saving Time", "", "UTC-08:00"),
    Abbreviation("AKST", "Alaska Standard Time", "North America", "UTC-09:00"),
    Abbreviation("AT", "Alaska Time", "", "UTC-09:00"),
    Abbreviation("ALMT", "Alma-Ata Time", "Asia", "UTC+06:00"),
    Abbreviation("AMST", "Amazon Summer Time", "South America", "UTC-03:00"),
    Abbreviation("AMST", "Armenia Summer Time", "Asia", "UTC+05:00"),
    Abbreviation("AMDT", "Armenia Daylight Time", "", "UTC+05:00"),
    Abbreviation("AMT", "Amazon Time", "South America", "UTC-04:00"),
    Abbreviation("AMT", "Armenia Time", "Asia", "UTC+04:00"),
    Abbreviation("ANAST", "Anadyr Summer Time", "Asia", "UTC+12:00"),
    Abbreviation("ANAT", "Anadyr Time", "Asia", "UTC+12:00"),
    Abbreviation("AQTT", "Aqtobe Time", "Asia", "UTC+05:00"),
    Abbreviation("ART", "Argentina Time", "South America", "UTC-03:00"),
    Abbreviation("AST", "Arabia Standard Time", "Asia", "UTC+03:00"),
    Abbreviation("AST", "Arabic Standard Time", "", "UTC+03:00"),
    Abbreviation("AST", "Al Manamah Standard Time", "", "UTC+03:00"),
    Abbreviation("AST", "Atlantic Standard Time", "North America", "UTC-04:00"),
    Abbreviation("AT", "Atlantic Time", "Atlantic", "UTC-04:00"),
    Abbreviation("AST", "Tiempo Estándar del Atlántico (Spanish)", "Caribbean", "UTC-04:00"),
    Abbreviation("HNA", "Heure Normale de l'Atlantique (French)", "", "UTC-04:00"),
    Abbreviation("AT", "Atlantic Time", "North America", "UTC-04:00 / -3:00"),
    Abbreviation("AWDT", "Australian Western Daylight Time", "Australia", "UTC+09:00"),
    Abbreviation("WDT", "Western Daylight Time", "", "UTC+09:00"),
    Abbreviation("WST", "Western Summer Time", "", "UTC+09:00"),
    Abbreviation("AWST", "Australian Western Standard Time", "Australia", "UTC+08:00"),
    Abbreviation("WST", "Western Standard Time", "", "UTC+08:00"),
    Abbreviation("WAT", "Western Australia Time", "", "UTC+08:00"),
    Abbreviation("AZOST", "Azores Summer Time", "Atlantic", "UTC+00:00"),
    Abbreviation("AZODT", "Azores Daylight Time", "", "UTC+00:00"),
    Abbreviation("AZOT", "Azores Time", "Atlantic", "UTC-01:00"),
    Abbreviation("AZOST", "Azores Standard Time", "", "UTC-01:00"),
    Abbreviation("AZST", "Azerbaijan Summer Time", "Asia", "UTC+05:00"),
    Abbreviation("AZT", "Azerbaijan Time", "Asia", "UTC+04:00"),
    Abbreviation("AoE", "Anywhere on Earth", "Pacific", "UTC-12:00"),
    Abbreviation("B", "Bravo Time Zone", "Military", "UTC+02:00"),
    Abbreviation("BNT", "Brunei Darussalam Time", "Asia", "UTC+08:00"),
    Abbreviation("BDT", "Brunei Time", "", "UTC+08:00"),
    Abbreviation("BOT", "Bolivia Time", "South America", "UTC-04:00"),
    Abbreviation("BRST", "Brasília Summer Time", "South America", "UTC-02:00"),
    Abbreviation("BST", "Brazil Summer Time", "", "UTC-02:00"),
    Abbreviation("BST", "Brazilian Summer Time", "", "UTC-02:00"),
    Abbreviation("BRT", "Brasília Time", "South America", "UTC-03:00"),
    Abbreviation("BT", "Brazil Time", "", "UTC-03:00"),
    Abbreviation("BT", "Brazilian Time", "", "UTC-03:00"),
    Abbreviation("BST", "Bangladesh Standard Time", "Asia", "UTC+06:00"),
    Abbreviation("BST", "Bougainville Standard Time", "Pacific", "UTC+11:00"),
    Abbreviation("BST", "British Summer Time", "Europe", "UTC+01:00"),
    Abbreviation("BDT", "British Daylight Time", "", "UTC+01:00"),
    Abbreviation("BDST", "British Daylight Saving Time", "", "UTC+01:00"),
    Abbreviation("BTT", "Bhutan Time", "Asia", "UTC+06:00"),
    Abbreviation("C", "Charlie Time Zone", "Military", "UTC+03:00"),
    Abbreviation("CAST", "Casey Time", "Antarctica", "UTC+08:00"),
    Abbreviation("CAT", "Central Africa Time", "Africa", "UTC+02:00"),
    Abbreviation("CCT", "Cocos Islands Time", "Indian Ocean", "UTC+06:30"),
    Abbreviation("CDT", "Central Daylight Time", "North America", "UTC-05:00"),
    Abbreviation("CDST", "Central Daylight Saving Time", "", "UTC-05:00"),
    Abbreviation("NACDT", "North American Central Daylight Time", "", "UTC-05:00"),
    Abbreviation("HAC", "Heure Avancée du Centre (French)", "", "UTC-05:00"),
    Abbreviation("CDT", "Cuba Daylight Time", "Caribbean", "UTC-04:00"),
    Abbreviation("CEST", "Central European Summer Time", "Europe", "UTC+02:00"),
    Abbreviation("CEDT", "Central European Daylight Time", "Antarctica", "UTC+02:00"),
    Abbreviation("ECST", "European Central Summer Time", "", "UTC+02:00"),
    Abbreviation("MESZ", "Mitteleuropäische Sommerzeit (German)", "", "UTC+02:00"),
    Abbreviation("CET", "Central European Time", "Europe", "UTC+01:00"),
    Abbreviation("ECT", "European Central Time", "Africa", "UTC+01:00"),
    Abbreviation("CET", "Central Europe Time", "Antarctica", "UTC+01:00"),
    Abbreviation("MEZ", "Mitteleuropäische Zeit (German)", "", "UTC+01:00"),
    Abbreviation("CHADT", "Chatham Island Daylight Time", "Pacific", "UTC+13:45"),
    Abbreviation("CDT", "Chatham Daylight Time", "", "UTC+13:45"),
    Abbreviation("CHAST", "Chatham Island Standard Time", "Pacific", "UTC+12:45"),
    Abbreviation("CHOT", "Choibalsan Time", "Asia", "UTC+08:00"),
    Abbreviation("CHUT", "Chuuk Time", "Pacific", "UTC+10:00"),
    Abbreviation("CKT", "Cook Island Time", "Pacific", "UTC-10:00"),
    Abbreviation("CLST", "Chile Summer Time", "South America", "UTC-03:00"),
    Abbreviation("CLDT", "Chile Daylight Time", "Antarctica", "UTC-03:00"),
    Abbreviation("CLT", "Chile Standard Time", "South America", "UTC-03:00"),
    Abbreviation("CT", "Chile Time", "Antarctica", "UTC-03:00"),
    Abbreviation("CLST", "Chile Standard Time", "", "UTC-03:00"),
    Abbreviation("COT", "Colombia Time", "South America", "UTC-05:00"),
    Abbreviation("CST", "Central Standard Time", "North America", "UTC-06:00"),
    Abbreviation("CT", "Central Time", "Central America", "UTC-06:00"),
    Abbreviation("NACST", "North American Central Standard Time", "", "UTC-06:00"),
    Abbreviation("CST", "Tiempo Central Estándar (Spanish)", "", "UTC-06:00"),
    Abbreviation("HNC", "Heure Normale du Centre (French)", "", "UTC-06:00"),
    Abbreviation("CST", "China Standard Time", "Asia", "UTC+08:00"),
    Abbreviation("CST", "Cuba Standard Time", "Caribbean", "UTC-05:00"),
    Abbreviation("CT", "Central Time", "North America", "UTC-06:00 / -5:00"),
    Abbreviation("CVT", "Cape Verde Time", "Africa", "UTC-01:00"),
    Abbreviation("CXT", "Christmas Island Time", "Australia", "UTC+07:00"),
    Abbreviation("ChST", "Chamorro Standard Time", "Pacific", "UTC+10:00"),
    Abbreviation("GST", "Guam Standard Time", "", "UTC+10:00"),
    Abbreviation("D", "Delta Time Zone", "Military", "UTC+04:00"),
    Abbreviation("DAVT", "Davis Time", "Antarctica", "UTC+07:00"),
    Abbreviation("DDUT", "Dumont-d'Urville Time", "Antarctica", "UTC+10:00"),
    Abbreviation("E", "Echo Time Zone", "Military", "UTC+05:00"),
    Abbreviation("EASST", "Easter Island Summer Time", "Pacific", "UTC-05:00"),
    Abbreviation("EADT", "Easter Island Daylight Time", "", "UTC-05:00"),
    Abbreviation("EAST", "Easter Island Standard Time", "Pacific", "UTC-05:00"),
    Abbreviation("EAT", "Eastern Africa Time", "Africa", "UTC+03:00"),
    Abbreviation("EAT", "East Africa Time", "Indian Ocean", "UTC+03:00"),
    Abbreviation("ECT", "Ecuador Time", "South America", "UTC-05:00"),
    Abbreviation("EDT", "Eastern Daylight Time", "North America", "UTC-04:00"),
    Abbreviation("EDST", "Eastern Daylight Savings Time", "Caribbean", "UTC-04:00"),
    Abbreviation("NAEDT", "North American Eastern Daylight Time", "", "UTC-04:00"),
    Abbreviation("HAE", "Heure Avancée de l'Est (French)", "", "UTC-04:00"),
    Abbreviation("EDT", "Tiempo de verano del Este (Spanish)", "", "UTC-04:00"),
    Abbreviation("EEST", "Eastern European Summer Time", "Europe", "UTC+03:00"),
    Abbreviation("EEDT", "Eastern European Daylight Time", "Asia", "UTC+03:00"),
    Abbreviation("OESZ", "Osteuropäische Sommerzeit (German)", "", "UTC+03:00"),
    Abbreviation("EET", "Eastern European Time", "Europe", "UTC+02:00"),
    Abbreviation("OEZ", "Osteuropäische Zeit (German)", "Asia", "UTC+02:00"),
    Abbreviation("EGST", "Eastern Greenland Summer Time", "North America", "UTC+00:00"),
    Abbreviation("EGST", "East Greenland Summer Time", "", "UTC+00:00"),
    Abbreviation("EGT", "East Greenland Time", "North America", "UTC-01:00"),
    Abbreviation("EGT", "Eastern Greenland Time", "", "UTC-01:00"),
    Abbreviation("EST", "Eastern Standard Time", "North America", "UTC-05:00"),
    Abbreviation("ET", "Eastern Time ", "Caribbean", "UTC-05:00"),
    Abbreviation("NAEST", "North American Eastern Standard Time", "Central America", "UTC-05:00"),
    Abbreviation("ET", "Tiempo del Este (Spanish)", "", "UTC-05:00"),
    Abbreviation("HNE", "Heure Normale de l'Est (French)", "", "UTC-05:00"),
    Abbreviation("ET", "Eastern Time", "North America", "UTC-05:00 / -4:00"),
    Abbreviation("F", "Foxtrot Time Zone", "Military", "UTC+06:00"),
    Abbreviation("FET", "Further-Eastern European Time", "Europe", "UTC+03:00"),
    Abbreviation("FJST", "Fiji Summer Time", "Pacific", "UTC+13:00"),
    Abbreviation("FJDT", "Fiji Daylight Time", "", "UTC+13:00"),
    Abbreviation("FJT", "Fiji Time", "Pacific", "UTC+12:00"),
    Abbreviation("FKST", "Falkland Islands Summer Time", "South America", "UTC-03:00"),
    Abbreviation("FKDT", "Falkland Island Daylight Time", "", "UTC-03:00"),
    Abbreviation("FKT", "Falkland Island Time", "South America", "UTC-04:00"),
    Abbreviation("FKST", "Falkland Island Standard Time", "", "UTC-04:00"),
    Abbreviation("FNT", "Fernando de Noronha Time", "South America", "UTC-02:00"),
    Abbreviation("G", "Golf Time Zone", "Military", "UTC+07:00"),
    Abbreviation("GALT", "Galapagos Time", "Pacific", "UTC-06:00"),
    Abbreviation("GAMT", "Gambier Time", "Pacific", "UTC-09:00"),
    Abbreviation("GAMT", "Gambier Islands Time", "", "UTC-09:00"),
    Abbreviation("GET", "Georgia Standard Time", "Asia", "UTC+04:00"),
    Abbreviation("GFT", "French Guiana Time", "South America", "UTC-03:00"),
    Abbreviation("GILT", "Gilbert Island Time", "Pacific", "UTC+12:00"),
    Abbreviation("GMT", "Greenwich Mean Time", "Europe", "UTC+00:00"),
    Abbreviation("UTC", "Coordinated Universal Time", "Africa", "UTC+00:00"),
    Abbreviation("GT", "Greenwich Time", "North America", "UTC+00:00"),
    Abbreviation("GST", "Gulf Standard Time", "Asia", "UTC+04:00"),
    Abbreviation("GST", "South Georgia Time", "South America", "UTC-02:00"),
    Abbreviation("GYT", "Guyana Time", "South America", "UTC-04:00"),
    Abbreviation("H", "Hotel Time Zone", "Military", "UTC+08:00"),
    Abbreviation("HADT", "Hawaii-Aleutian Daylight Time", "North America", "UTC-09:00"),
    Abbreviation("HDT", "Hawaii Daylight Time", "", "UTC-09:00"),
    Abbreviation("HAST", "Hawaii-Aleutian Standard Time", "North America", "UTC-10:00"),
    Abbreviation("HST", "Hawaii Standard Time", "Pacific", "UTC-10:00"),
    Abbreviation("HKT", "Hong Kong Time", "Asia", "UTC+08:00"),
    Abbreviation("HOVT", "Hovd Time", "Asia", "UTC+07:00"),
    Abbreviation("I", "India Time Zone", "Military", "UTC+09:00"),
    Abbreviation("ICT", "Indochina Time", "Asia", "UTC+07:00"),
    Abbreviation("IDT", "Israel Daylight Time", "Asia", "UTC+03:00"),
    Abbreviation("IOT", "Indian Chagos Time", "Indian Ocean", "UTC+06:00"),
    Abbreviation("IRDT", "Iran Daylight Time", "Asia", "UTC+04:30"),
    Abbreviation("IRST", "Iran Summer Time", "", "UTC+04:30"),
    Abbreviation("IDT", "Iran Daylight Time", "", "UTC+04:30"),
    Abbreviation("IRKST", "Irkutsk Summer Time", "Asia", "UTC+09:00"),
    Abbreviation("IRKT", "Irkutsk Time", "Asia", "UTC+08:00"),
    Abbreviation("IRST", "Iran Standard Time", "Asia", "UTC+03:30"),
    Abbreviation("IT", "Iran Time", "", "UTC+03:30"),
    Abbreviation("IST", "India Standard Time", "Asia", "UTC+05:30"),
    Abbreviation("IT", "India Time", "", "UTC+05:30"),
    Abbreviation("IST", "Indian Standard Time", "", "UTC+05:30"),
    Abbreviation("IST", "Irish Standard Time", "Europe", "UTC+01:00"),
    Abbreviation("IST", "Irish Summer Time", "", "UTC+01:00"),
    Abbreviation("IST", "Israel Standard Time", "Asia", "UTC+02:00"),
    Abbreviation("JST", "Japan Standard Time", "Asia", "UTC+09:00"),
    Abbreviation("K", "Kilo Time Zone", "Military", "UTC+10:00"),
    Abbreviation("KGT", "Kyrgyzstan Time", "Asia", "UTC+06:00"),
    Abbreviation("KOST", "Kosrae Time", "Pacific", "UTC+11:00"),
    Abbreviation("KRAST", "Krasnoyarsk Summer Time", "Asia", "UTC+08:00"),
    Abbreviation("KRAT", "Krasnoyarsk Time", "Asia", "UTC+07:00"),
    Abbreviation("KST", "Korea Standard Time", "Asia", "UTC+09:00"),
    Abbreviation("KST", "Korean Standard Time", "", "UTC+09:00"),
    Abbreviation("KT", "Korea Time", "", "UTC+09:00"),
    Abbreviation("KUYT", "Kuybyshev Time", "Europe", "UTC+04:00"),
    Abbreviation("SAMST", "Samara Summer Time", "", "UTC+04:00"),
    Abbreviation("L", "Lima Time Zone", "Military", "UTC+11:00"),
    Abbreviation("LHDT", "Lord Howe Daylight Time", "Australia", "UTC+11:00"),
    Abbreviation("LHST", "Lord Howe Standard Time", "Australia", "UTC+10:30"),
    Abbreviation("LINT", "Line Islands Time", "Pacific", "UTC+14:00"),
    Abbreviation("M", "Mike Time Zone", "Military", "UTC+12:00"),
    Abbreviation("MAGST", "Magadan Summer Time", "Asia", "UTC+12:00"),
    Abbreviation("MAGST", "Magadan Island Summer Time", "", "UTC+12:00"),
    Abbreviation("MAGT", "Magadan Time", "Asia", "UTC+10:00"),
    Abbreviation("MAGT", "Magadan Island Time", "", "UTC+10:00"),
    Abbreviation("MART", "Marquesas Time", "Pacific", "UTC-09:30"),
    Abbreviation("MAWT", "Mawson Time", "Antarctica", "UTC+05:00"),
    Abbreviation("MDT", "Mountain Daylight Time", "North America", "UTC-06:00"),
    Abbreviation("MDST", "Mountain Daylight Saving Time", "", "UTC-06:00"),
    Abbreviation("NAMDT", "North American Mountain Daylight Time", "", "UTC-06:00"),
    Abbreviation("HAR", "Heure Avancée des Rocheuses (French)", "", "UTC-06:00"),
    Abbreviation("MET", "Middle European Time", "Europe", "UTC+01:00"),
    Abbreviation("MEST", "Middle European Summer Time", "Europe", "UTC+02:00"),
    Abbreviation("MHT", "Marshall Islands Time", "Pacific", "UTC+12:00"),
    Abbreviation("MMT", "Myanmar Time", "Asia", "UTC+06:30"),
    Abbreviation("MSD", "Moscow Daylight Time", "Europe", "UTC+04:00"),
    Abbreviation("MSK", "Moscow Standard Time", "Europe", "UTC+03:00"),
    Abbreviation("MCK", "Moscow Time", "Asia", "UTC+03:00"),
    Abbreviation("MST", "Mountain Standard Time", "North America", "UTC-07:00"),
    Abbreviation("MT", "Mountain Time", "", "UTC-07:00"),
    Abbreviation("NAMST", "North American Mountain Standard Time", "", "UTC-07:00"),
    Abbreviation("HNR", "Heure Normale des Rocheuses (French)", "", "UTC-07:00"),
    Abbreviation("MT", "Mountain Time", "North America", "UTC-07:00 / -6:00"),
    Abbreviation("MUT", "Mauritius Time", "Africa", "UTC+04:00"),
    Abbreviation("MVT", "Maldives Time", "Asia", "UTC+05:00"),
    Abbreviation("MYT", "Malaysia Time", "Asia", "UTC+08:00"),
    Abbreviation("MST", "Malaysian Standard Time", "", "UTC+08:00"),
    Abbreviation("N", "November Time Zone", "Military", "UTC-01:00"),
    Abbreviation("NCT", "New Caledonia Time", "Pacific", "UTC+11:00"),
    Abbreviation("NDT", "Newfoundland Daylight Time", "North America", "UTC-02:30"),
    Abbreviation("HAT", "Heure Avancée de Terre-Neuve (French)", "", "UTC-02:30"),
    Abbreviation("NFT", "Norfolk Time", "Australia", "UTC+11:30"),
    Abbreviation("NFT", "Norfolk Island Time", "", "UTC+11:30"),
    Abbreviation("NOVST", "Novosibirsk Summer Time", "Asia", "UTC+07:00"),
    Abbreviation("OMSST", "Omsk Summer Time", "", "UTC+07:00"),
    Abbreviation("NOVT", "Novosibirsk Time", "Asia", "UTC+06:00"),
    Abbreviation("OMST", "Omsk Standard Time", "", "UTC+06:00"),
    Abbreviation("NPT", "Nepal Time", "Asia", "UTC+05:45"),
    Abbreviation("NRT", "Nauru Time", "Pacific", "UTC+12:00"),
    Abbreviation("NST", "Newfoundland Standard Time", "North America", "UTC-03:30"),
    Abbreviation("HNT", "Heure Normale de Terre-Neuve (French)", "", "UTC-03:30"),
    Abbreviation("NUT", "Niue Time", "Pacific", "UTC-11:00"),
    Abbreviation("NZDT", "New Zealand Daylight Time", "Pacific", "UTC+13:00"),
    Abbreviation("NZST", "New Zealand Standard Time", "Pacific", "UTC+12:00"),
    Abbreviation("O", "Oscar Time Zone", "Military", "UTC-02:00"),
    Abbreviation("OMSST", "Omsk Summer Time", "Asia", "UTC+07:00"),
    Abbreviation("NOVST", "Novosibirsk Summer Time", "", "UTC+07:00"),
    Abbreviation("OMST", "Omsk Standard Time", "Asia", "UTC+06:00"),
    Abbreviation("OMST", "Omsk Time", "", "UTC+06:00"),
    Abbreviation("NOVT", "Novosibirsk Time", "", "UTC+06:00"),
    Abbreviation("ORAT", "Oral Time", "Asia", "UTC+05:00"),
    Abbreviation("P", "Papa Time Zone", "Military", "UTC-03:00"),
    Abbreviation("PDT", "Pacific Daylight Time", "North America", "UTC-07:00"),
    Abbreviation("PDST", "Pacific Daylight Saving Time", "", "UTC-07:00"),
    Abbreviation("NAPDT", "North American Pacific Daylight Time", "", "UTC-07:00"),
    Abbreviation("HAP", "Heure Avancée du Pacifique (French)", "", "UTC-07:00"),
    Abbreviation("PET", "Peru Time", "South America", "UTC-05:00"),
    Abbreviation("PETST", "Kamchatka Summer Time", "Asia", "UTC+12:00"),
    Abbreviation("PETT", "Kamchatka Time", "Asia", "UTC+12:00"),
    Abbreviation("PETT", "Petropavlovsk-Kamchatski Time", "", "UTC+12:00"),
    Abbreviation("PGT", "Papua New Guinea Time", "Pacific", "UTC+10:00"),
    Abbreviation("PHOT", "Phoenix Island Time", "Pacific", "UTC+13:00"),
    Abbreviation("PHT", "Philippine Time", "Asia", "UTC+08:00"),
    Abbreviation("PST", "Philippine Standard Time", "", "UTC+08:00"),
    Abbreviation("PKT", "Pakistan Standard Time", "Asia", "UTC+05:00"),
    Abbreviation("PKT", "Pakistan Time", "", "UTC+05:00"),
    Abbreviation("PMDT", "Pierre & Miquelon Daylight Time", "North America", "UTC-02:00"),
    Abbreviation("PMST", "Pierre & Miquelon Standard Time", "North America", "UTC-03:00"),
    Abbreviation("PONT", "Pohnpei Standard Time", "Pacific", "UTC+11:00"),
    Abbreviation("PST", "Pacific Standard Time", "North America", "UTC-08:00"),
    Abbreviation("PT", "Pacific Time", "", "UTC-08:00"),
    Abbreviation("NAPST", "North American Pacific Standard Time", "", "UTC-08:00"),
    Abbreviation("PT", "Tiempo del Pacífico (Spanish)", "", "UTC-08:00"),
    Abbreviation("HNP", "Heure Normale du Pacifique (French)", "", "UTC-08:00"),
    Abbreviation("PST", "Pitcairn Standard Time", "Pacific", "UTC-08:00"),
    Abbreviation("PT", "Pacific Time", "North America", "UTC-08:00 / -7:00"),
    Abbreviation("PWT", "Palau Time", "Pacific", "UTC+09:00"),
    Abbreviation("PYST", "Paraguay Summer Time", "South America", "UTC-03:00"),
    Abbreviation("PYT", "Paraguay Time", "South America", "UTC-04:00"),
    Abbreviation("Q", "Quebec Time Zone", "Military", "UTC-04:00"),
    Abbreviation("QYZT", "Qyzylorda Time", "Asia", "UTC+06:00"),
    Abbreviation("R", "Romeo Time Zone", "Military", "UTC-05:00"),
    Abbreviation("RET", "Reunion Time", "Africa", "UTC+04:00"),
    Abbreviation("ROTT", "Rothera Time", "Antarctica", "UTC-03:00"),
    Abbreviation("S", "Sierra Time Zone", "Military", "UTC-06:00"),
    Abbreviation("SAKT", "Sakhalin Time", "Asia", "UTC+10:00"),
    Abbreviation("SAMT", "Samara Time", "Europe", "UTC+04:00"),
    Abbreviation("SAMT", "Samara Standard Time", "", "UTC+04:00"),
    Abbreviation("SAST", "South Africa Standard Time", "Africa", "UTC+02:00"),
    Abbreviation("SAST", "South African Standard Time", "", "UTC+02:00"),
    Abbreviation("SBT", "Solomon Islands Time", "Pacific", "UTC+11:00"),
    Abbreviation("SBT", "Solomon Island Time", "", "UTC+11:00"),
    Abbreviation("SCT", "Seychelles Time", "Africa", "UTC+04:00"),
    Abbreviation("SGT", "Singapore Time", "Asia", "UTC+08:00"),
    Abbreviation("SST", "Singapore Standard Time", "", "UTC+08:00"),
    Abbreviation("SRET", "Srednekolymsk Time", "Asia", "UTC+11:00"),
    Abbreviation("SRT", "Suriname Time", "South America", "UTC-03:00"),
    Abbreviation("SST", "Samoa Standard Time", "Pacific", "UTC-11:00"),
    Abbreviation("SYOT", "Syowa Time", "Antarctica", "UTC+03:00"),
    Abbreviation("T", "Tango Time Zone", "Military", "UTC-07:00"),
    Abbreviation("TAHT", "Tahiti Time", "Pacific", "UTC-10:00"),
    Abbreviation("TFT", "French Southern and Antarctic Time", "Indian Ocean", "UTC+05:00"),
    Abbreviation("KIT", "Kerguelen (Islands) Time", "", "UTC+05:00"),
    Abbreviation("TJT", "Tajikistan Time", "Asia", "UTC+05:00"),
    Abbreviation("TKT", "Tokelau Time", "Pacific", "UTC+13:00"),
    Abbreviation("TLT", "East Timor Time", "Asia", "UTC+09:00"),
    Abbreviation("TMT", "Turkmenistan Time", "Asia", "UTC+05:00"),
    Abbreviation("TOT", "Tonga Time", "Pacific", "UTC+13:00"),
    Abbreviation("TVT", "Tuvalu Time", "Pacific", "UTC+12:00"),
    Abbreviation("U", "Uniform Time Zone", "Military", "UTC-08:00"),
    Abbreviation("ULAT", "Ulaanbaatar Time", "Asia", "UTC+08:00"),
    Abbreviation("ULAT", "Ulan Bator Time", "", "UTC+08:00"),
    Abbreviation("UTC", "Coordinated Universal Time", "Worldwide", "UTC"),
    Abbreviation("UYST", "Uruguay Summer Time", "South America", "UTC-02:00"),
    Abbreviation("UYT", "Uruguay Time", "South America", "UTC-03:00"),
    Abbreviation("UZT", "Uzbekistan Time", "Asia", "UTC+05:00"),
    Abbreviation("V", "Victor Time Zone", "Military", "UTC-09:00"),
    Abbreviation("VET", "Venezuelan Standard Time", "South America", "UTC-04:30"),
    Abbreviation("HLV", "Hora Legal de Venezuela (Spanish)", "", "UTC-04:30"),
    Abbreviation("VLAST", "Vladivostok Summer Time", "Asia", "UTC+11:00"),
    Abbreviation("VLAT", "Vladivostok Time", "Asia", "UTC+10:00"),
    Abbreviation("VOST", "Vostok Time", "Antarctica", "UTC+06:00"),
    Abbreviation("VUT", "Vanuatu Time", "Pacific", "UTC+11:00"),
    Abbreviation("EFATE", "Efate Time", "", "UTC+11:00"),
    Abbreviation("W", "Whiskey Time Zone", "Military", "UTC-10:00"),
    Abbreviation("WAKT", "Wake Time", "Pacific", "UTC+12:00"),
    Abbreviation("WARST", "Western Argentine Summer Time", "South America", "UTC-03:00"),
    Abbreviation("WAST", "West Africa Summer Time", "Africa", "UTC+02:00"),
    Abbreviation("WAT", "West Africa Time", "Africa", "UTC+01:00"),
    Abbreviation("WEST", "Western European Summer Time", "Europe", "UTC+01:00"),
    Abbreviation("WEDT", "Western European Daylight Time", "Africa", "UTC+01:00"),
    Abbreviation("WESZ", "Westeuropäische Sommerzeit (German)", "", "UTC+01:00"),
    Abbreviation("WET", "Western European Time", "Europe", "UTC+00:00"),
    Abbreviation("GMT", "Greenwich Mean Time", "Africa", "UTC+00:00"),
    Abbreviation("WEZ", "Westeuropäische Zeit (German)", "", "UTC+00:00"),
    Abbreviation("WFT", "Wallis and Futuna Time", "Pacific", "UTC+12:00"),
    Abbreviation("WGST", "Western Greenland Summer Time", "North America", "UTC-02:00"),
    Abbreviation("WGST", "West Greenland Summer Time", "", "UTC-02:00"),
    Abbreviation("WGT", "West Greenland Time", "North America", "UTC-03:00"),
    Abbreviation("WGT", "Western Greenland Time", "", "UTC-03:00"),
    Abbreviation("WIB", "Western Indonesian Time", "Asia", "UTC+07:00"),
    Abbreviation("WIB", "Waktu Indonesia Barat", "", "UTC+07:00"),
    Abbreviation("WIT", "Eastern Indonesian Time", "Asia", "UTC+09:00"),
    Abbreviation("WIT", "Waktu Indonesia Timur", "", "UTC+09:00"),
    Abbreviation("WITA", "Central Indonesian Time", "Asia", "UTC+08:00"),
    Abbreviation("WITA", "Waktu Indonesia Tengah", "", "UTC+08:00"),
    Abbreviation("WST", "West Samoa Time", "Pacific", "UTC+13:00"),
    Abbreviation("ST", "Samoa Time", "", "UTC+13:00"),
    Abbreviation("WST", "Western Sahara Summer Time", "Africa", "UTC+01:00"),
    Abbreviation("WT", "Western Sahara Standard Time", "Africa", "UTC+00:00"),
    Abbreviation("WT", "Western Sahara Time", "", "UTC+00:00"),
    Abbreviation("X", "X-ray Time Zone", "Military", "UTC-11:00"),
    Abbreviation("Y", "Yankee Time Zone", "Military", "UTC-12:00"),
    Abbreviation("YAKST", "Yakutsk Summer Time", "Asia", "UTC+10:00"),
    Abbreviation("YAKT", "Yakutsk Time", "Asia", "UTC+09:00"),
    Abbreviation("YAPT", "Yap Time", "Pacific", "UTC+10:00"),
    Abbreviation("YEKST", "Yekaterinburg Summer Time", "Asia", "UTC+06:00"),
    Abbreviation("YEKT", "Yekaterinburg Time", "Asia", "UTC+05:00"),
    Abbreviation("Z", "Zulu Time Zone", "Military", "UTC+00:00")
  )
  val groupedAbbrevations = abbreviations.groupBy(_.abbreviation)
}