language: generic

sudo: required

services:
  - docker

install:
  - docker build -t thymeflow/back .

script:
  - docker run thymeflow/back sbt test

deploy:
  provider: script
  script: bash docker_push.sh thymeflow/back
  on:
    branch: master
